server:
  port: 8080 # Specify the port on which the microservice will run

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patientdb # Database Url
    username: root
    password: 0823


  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update


